import json
from tools.vision import VisionTool
from tools.equity import EquityRiskTool 
# from tools.guidelines import GuidelinesTool (Future)

class ToolRegistry:
    def __init__(self):
        # Initialize the actual tools (The "Experts")
        # Ensure your VisionTool in tools/vision.py handles initialization gracefully
        self.vision = VisionTool(model_path="checkpoints/best_fair_eye_model.pth") 
        self.equity = EquityRiskTool()

    def get_schemas(self):
        """
        Returns the JSON schemas strictly formatted for OpenAI function calling.
        """
        return [
            {
                "type": "function",
                "function": {
                    "name": "consult_vision_expert",
                    "description": "Send a fundus image to the RETFound AI specialist for probabilistic disease detection.",
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "image_path": {"type": "string", "description": "Absolute path to the patient's scan."}
                        },
                        "required": ["image_path"]
                    }
                }
            },
            {
                "type": "function",
                "function": {
                    "name": "consult_equity_expert",
                    "description": "Query the fairness database for demographic-specific risk factors, prevalence data, and potential model biases.",
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "disease": {"type": "string", "description": "The suspected disease (e.g., 'Glaucoma', 'DR', 'AMD')."},
                            "race": {"type": "string", "description": "Patient's race/ethnicity."},
                            "age": {"type": "integer", "description": "Patient's age."}
                        },
                        "required": ["disease", "race", "age"]
                    }
                }
            }
        ]

    def execute(self, tool_call):
        """
        Parses the LLM's request and routes it to the correct Python class.
        """
        func_name = tool_call.function.name
        try:
            args = json.loads(tool_call.function.arguments)
        except json.JSONDecodeError:
            return {"error": "Invalid JSON arguments generated by LLM."}

        print(f"   [Registry] Routing call: {func_name} with {args}")

        if func_name == "consult_vision_expert":
            # Delegate to tools/vision.py
            return self.vision.predict(args["image_path"])

        elif func_name == "consult_equity_expert":
            # Delegate to tools/equity.py
            return self.equity.check_risk(args["disease"], args["race"], args.get("age"))

        else:
            return {"error": f"Tool '{func_name}' not found in registry."}